### ISSUE TITLE
Android 10 support

### ISSUE THREAD

**Issue by tombriden** [Magisk-Modules-Repo/gjf_bt#7] opened 2019-10-01 13:19 UTC
Hi,
The module installs fine on Android 10 but any time audio is about to be played, "bluetooth" crashes and the headphones get disconnected. 
Any chance you can bring the module up to date for 10? Or give me some direction on how you got this working and I'll have a go myself?
Cheers

**Comment by moist-turkey** [comment] 2019-10-15 11:32
Same here. **SBC works fine** but when I connect a pair of APTx headphones I get a bluetooth crash - which leads me to believe that module may be increasing the SBC bit-rate as expected but the APTx enabler aspect of the module may be causing issues.

As an interim measure is it perhaps worth adding a volume toggle for 'install APTx library?' - I think this may be the cause of the issue.

**Comment by gjf** [comment] 2020-02-04 14:41
Possibly your devices are not supported. I am pretty sure Android 10 won't be supported at all.

**Closed by gjf** 2020-02-04 14:41 UTC
